/*
First start by taking a snapshot of your most important database: production. This will be the starting point for migrations.

Generate a sql script that includes the entire DDL (including indexes, triggers, procedures, ...) of the production database. 
To do this you will need to add insert statements for all the reference data present in the database. 
*/

/*
drop table project if exists;
drop table role if exists;
drop table user if exists;
create table project (id bigint generated by default as identity, description varchar(255), name varchar(255), primary key (id));
create table role (id bigint generated by default as identity, role integer, user_id bigint, primary key (id));
create table user (id bigint generated by default as identity, account_expired boolean not null, account_locked boolean not null, email varchar(255), enabled boolean not null, password varchar(255), username varchar(255), primary key (id));
alter table user add constraint UK_email  unique (email);
alter table role add constraint FK_UserId foreign key (user_id) references user;
*/

